name: MinecraftDashboard
main: de.gnmyt.mcdash.MinecraftDashboard
version: 1.4
api-version: 1.13
description: This is the official plugin (wrapper) for MCDash, a free and open-source minecraft dashboard.
author: GNMYT